# Generated by Django 5.1.2 on 2024-10-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("cnpj", models.IntegerField()),
                ("endereco", models.CharField(max_length=500)),
                ("bairro", models.CharField(max_length=50)),
                ("cidade", models.CharField(max_length=50)),
                ("uf", models.CharField(max_length=2)),
                ("telefone", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("tipo_de_produto", models.CharField(max_length=200)),
                ("sobre_produto", models.CharField(max_length=500)),
                ("transportadora_principal", models.CharField(max_length=300)),
                (
                    "custo_medio_de_compra",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "outras_informações",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
