# Generated by Django 5.0.6 on 2024-10-27 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(14)]),
        ),
    ]
