# Generated by Django 5.0.6 on 2024-10-27 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_alter_fornecedor_cnpj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fornecedor",
            name="telefone",
            field=models.CharField(
                max_length=15,
                validators=[django.core.validators.MinLengthValidator(11)],
            ),
        ),
    ]
