# Generated by Django 5.0.6 on 2024-10-27 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0004_alter_fornecedor_uf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fornecedor",
            name="custo_medio_de_compra",
        ),
        migrations.RemoveField(
            model_name="fornecedor",
            name="sobre_produto",
        ),
        migrations.RemoveField(
            model_name="fornecedor",
            name="tipo_de_produto",
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_do_produto", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=500)),
                (
                    "preco",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "custo_medio_de_compra",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos",
                        to="todos.fornecedor",
                    ),
                ),
            ],
        ),
    ]
