# Generated by Django 5.0.6 on 2024-10-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_fornecedor_outras_opcoes_de_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
