# Generated by Django 5.0.6 on 2024-10-31 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_fornecedor_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='outras_informações',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='outras_indormacoes',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Outras Informações'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='outras_opcoes_de_contato',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Outras Opções de Contato'),
        ),
    ]
